version: '3.9'

services:
  postgres:
    image: postgres:13.1-alpine
    container_name: postgres
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:rw

  nginx:
    build: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - todo_list_data:/todo_list/static
      - ./log:/var/log/nginx
    depends_on:
      - todo_list

  todo_list:
    build: ./todo_list
    container_name: todo_list
    restart: on-failure
    command: sh -c "/todo_list/entrypoint.sh"
    volumes:
      - ./todo_list/:/todo_list/
      - todo_list_data:/todo_list/static
    ports:
      - "8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
  todo_list_data:
    driver: local
